# Generated by Django 4.2.7 on 2025-05-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='photoUrl',
        ),
    ]
