# Generated by Django 5.1.5 on 2025-02-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=50)),
                ('stat', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TypesTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville_depart', models.CharField(max_length=100)),
                ('date_depart', models.DateTimeField()),
                ('ville_arrive', models.CharField(max_length=100)),
                ('date_arrive_prevu', models.DateTimeField()),
                ('date_arrive_reel', models.DateTimeField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('place', models.IntegerField()),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourOperateur.agencevoyage')),
                ('type_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages_unique', to='TourOperateur.typestransport')),
                ('types_transport', models.ManyToManyField(related_name='voyages_multiples', to='TourOperateur.typestransport')),
            ],
        ),
    ]
