# Generated by Django 5.1.5 on 2025-03-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgenceVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=50)),
                ('stat', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('place', models.IntegerField()),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='TourOperateur.agencevoyage')),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=100)),
                ('date_depart', models.DateTimeField()),
                ('ville_arrive', models.CharField(max_length=100)),
                ('date_arrive_prevu', models.DateTimeField()),
                ('date_arrive_reel', models.DateTimeField(blank=True, null=True)),
                ('types_transport', models.ManyToManyField(related_name='trajets', to='TourOperateur.typestransport')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='TourOperateur.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TourOperateur.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('view', 'Consulté'), ('like', 'Aimé'), ('favorite', 'Favori')], max_length=50)),
                ('date_interaction', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='TourOperateur.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='AvisVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='TourOperateur.voyage')),
            ],
        ),
    ]
