# Generated by Django 5.1.5 on 2025-02-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0002_avisvoyage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencevoyage',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences_responsables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='TourOperateur.agencevoyage'),
        ),
    ]
