# Generated by Django 5.1.5 on 2025-02-06 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0003_agencevoyage_responsable_alter_voyage_agence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='type_transport',
        ),
        migrations.AlterField(
            model_name='agencevoyage',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='types_transport',
            field=models.ManyToManyField(related_name='voyages', to='TourOperateur.typestransport'),
        ),
    ]
