# Generated by Django 4.2.7 on 2025-04-27 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(help_text='Latitude en degrés décimaux (WGS 84)')),
                ('longitude', models.FloatField(help_text='Longitude en degrés décimaux (WGS 84)')),
                ('image', models.ImageField(blank=True, help_text='Image principale de la destination', null=True, upload_to='destinations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pays', 'nom'],
                'unique_together': {('nom', 'pays')},
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ville_depart', models.CharField(max_length=200)),
                ('date_depart', models.DateField()),
                ('date_arrive', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacite', models.PositiveIntegerField()),
                ('places_disponibles', models.PositiveIntegerField()),
                ('niveau_confort', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('est_populaire', models.BooleanField(default=False)),
                ('est_recommande', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.JSONField(blank=True, default=list, help_text="Liste d'URLs d'images pour ce voyage", null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='voyages.destination')),
            ],
            options={
                'verbose_name': 'voyage',
                'verbose_name_plural': 'voyages',
                'ordering': ['date_depart'],
            },
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('est_inclus', models.BooleanField(default=True, help_text='Si faux, cela représente une exclusion')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'inclusion/exclusion',
                'verbose_name_plural': 'inclusions/exclusions',
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree', models.DurationField(help_text="Durée estimée de l'activité")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activites/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('est_optionnelle', models.BooleanField(default=False, help_text="Si l'activité est optionnelle (supplément possible)")),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='voyages.destination')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveIntegerField()),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('activite', models.TextField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('repas_inclus', models.CharField(blank=True, help_text='Décrire les repas inclus ce jour-là', max_length=100)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_jour', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'programme jour',
                'verbose_name_plural': 'programmes jour',
                'ordering': ['jour'],
                'unique_together': {('voyage', 'jour')},
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('est_approuve', models.BooleanField(default=False, help_text="L'avis a-t-il été approuvé par un modérateur?")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-date_creation'],
                'unique_together': {('voyage', 'utilisateur')},
            },
        ),
    ]
