# Generated by Django 4.2.7 on 2025-04-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_historiqueconsultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'type de voyage',
                'verbose_name_plural': 'types de voyage',
            },
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='capacite',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='date_arrive',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='places_disponibles',
        ),
        migrations.AddField(
            model_name='voyage',
            name='capacite_maximale',
            field=models.PositiveIntegerField(default=10, help_text='Nombre maximal de participants'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='nb_consultations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_depart',
            field=models.DateField(help_text='Date de départ du voyage'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='type_voyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='voyages.typevoyage'),
        ),
    ]
