# Generated by Django 4.2.7 on 2025-04-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0004_typevoyage_remove_voyage_capacite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyage',
            options={'verbose_name': 'voyage', 'verbose_name_plural': 'voyages'},
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='capacite_maximale',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='date_depart',
        ),
        migrations.CreateModel(
            name='DestinationFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='voyages.destination')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('destination', 'year', 'month')},
            },
        ),
    ]
