# Generated by Django 4.2.7 on 2025-05-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_alter_voyage_options_remove_voyage_capacite_maximale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueconsultation',
            options={'ordering': ['-date_consultation']},
        ),
    ]
