# Generated by Django 4.2.7 on 2025-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0006_alter_historiqueconsultation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='images',
            field=models.ImageField(blank=True, help_text='Image principale du voyages', null=True, upload_to='voyages/'),
        ),
    ]
