# Generated by Django 4.2.7 on 2025-05-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0007_alter_voyage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='images',
            new_name='image',
        ),
    ]
