# Generated by Django 4.2.7 on 2025-05-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0008_rename_images_voyage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='image',
            new_name='images',
        ),
    ]
