# Generated by Django 4.2.7 on 2025-04-29 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0004_typevoyage_remove_voyage_capacite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='est_confirmee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_personnes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('voyage', 'utilisateur')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='commentaires',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
    ]
