# Generated by Django 4.2.7 on 2025-05-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_est_confirmee_reservation_nombre_enfants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='nombre_personnes',
            new_name='nombre_adultes',
        ),
    ]
