# Generated by Django 4.2.7 on 2025-05-02 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voyages', '0006_alter_historiqueconsultation_options'),
        ('reservations', '0003_rename_nombre_personnes_reservation_nombre_adultes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_reservation'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Demandes spéciales'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Détails techniques'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('carte', 'Carte de crédit'), ('virement', 'Virement bancaire'), ('paypal', 'PayPal'), ('especes', 'Espèces')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='Référence transaction'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='reservations.reservation', verbose_name='Réservation associée'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('rembourse', 'Remboursé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='est_confirmee',
            field=models.BooleanField(default=False, verbose_name='Confirmée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_adultes',
            field=models.PositiveIntegerField(default=1, verbose_name="Nombre d'adultes"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voyages.voyage', verbose_name='Voyage associé'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(check=models.Q(('montant__gt', 0)), name='montant_paiement_positif'),
        ),
    ]
