# Generated by Django 4.2.7 on 2025-05-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_paiement_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
