# Generated by Django 4.2.7 on 2025-05-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_statut'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('reservation',)},
        ),
    ]
