# Generated by Django 4.2.7 on 2025-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_paiement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_depart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de depart'),
        ),
    ]
