# Generated by Django 4.2.7 on 2025-05-13 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_date_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='Référence transaction'),
        ),
    ]
