# Generated by Django 4.2.7 on 2025-05-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_paiement_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'annulee'), _negated=True), fields=('utilisateur', 'voyage'), name='unique_user_voyage'),
        ),
    ]
