# Generated by Django 4.2.7 on 2025-05-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact_estime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cout_implementation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefice_potentiel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('details', models.JSONField(default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_implementee', models.BooleanField(default=False)),
                ('date_implementation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-impact_estime'],
            },
        ),
        migrations.CreateModel(
            name='TravelTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('variation_pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('nombre_reservations', models.IntegerField()),
                ('revenu_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_en_hausse', models.BooleanField()),
                ('facteurs', models.JSONField(default=list)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-variation_pourcentage'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('tendance', 'Tendance'), ('recommandation', 'Recommandation'), ('alerte', 'Alerte'), ('opportunite', 'Opportunité')], max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actions_recommandees', models.JSONField(default=list)),
                ('metriques', models.JSONField(default=dict)),
                ('est_lu', models.BooleanField(default=False)),
                ('est_archive', models.BooleanField(default=False)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='finances.rapportfinancier')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
