# Generated by Django 5.1.5 on 2025-03-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='views_count',
        ),
    ]
