# Generated by Django 5.1.5 on 2025-02-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Client'), (2, 'Responsable'), (3, 'Admin')], default=1),
        ),
    ]
