# Generated by Django 4.2.7 on 2025-04-27 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('raisons', models.JSONField(default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('vue', models.BooleanField(default=False)),
                ('cliquee', models.BooleanField(default=False)),
                ('reservee', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='voyages.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_voyage_min', models.IntegerField(blank=True, help_text='Durée minimale en jours', null=True)),
                ('duree_voyage_max', models.IntegerField(blank=True, help_text='Durée maximale en jours', null=True)),
                ('interets', models.JSONField(default=list)),
                ('saisons_preferees', models.JSONField(default=list)),
                ('types_hebergement', models.JSONField(default=list)),
                ('activites_preferees', models.JSONField(default=list)),
                ('voyageur_avec', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations_favorites', models.ManyToManyField(blank=True, related_name='favoris_de', to='voyages.destination')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertinence', models.IntegerField(choices=[(1, 'Pas du tout pertinent'), (2, 'Peu pertinent'), (3, 'Moyennement pertinent'), (4, 'Pertinent'), (5, 'Très pertinent')])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recommandation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommandations.recommandation')),
            ],
        ),
    ]
