# Generated by Django 4.2.7 on 2025-04-27 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voyages', '0001_initial'),
        ('reservations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense'), ('remboursement', 'Remboursement')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.reservation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='voyages.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('periode', models.CharField(choices=[('jour', 'Jour'), ('semaine', 'Semaine'), ('mois', 'Mois'), ('trimestre', 'Trimestre'), ('annee', 'Année'), ('personnalise', 'Personnalisé')], max_length=20)),
                ('revenus_totaux', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depenses_totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('benefice_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.JSONField(default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('revenus_prevus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depenses_prevues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('benefice_prevu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.JSONField(default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
