# Generated by Django 4.2.7 on 2025-05-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('abandon', 'Panier abandonné'), ('promotion', 'Promotion'), ('rappel', 'Rappel'), ('avis', 'Avis'), ('fidelite', 'Fidélité')], max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('variables', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('abandon', 'Panier abandonné'), ('promotion', 'Promotion'), ('rappel', 'Rappel'), ('avis', 'Avis'), ('fidelite', 'Fidélité')], max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planifiee', 'Planifiée')], default='inactive', max_length=20)),
                ('delai', models.PositiveIntegerField(blank=True, null=True)),
                ('date_prochaine_execution', models.DateTimeField(blank=True, null=True)),
                ('date_derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('destinataires', models.PositiveIntegerField(default=0)),
                ('taux_ouverture', models.FloatField(blank=True, null=True)),
                ('taux_conversion', models.FloatField(blank=True, null=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagnes.modeleemail')),
            ],
        ),
    ]
